### ISSUE TITLE
Replace Description TextArea

### ISSUE THREAD

**Issue by lenghuang** [MLforALL-app/MLforALL#55]
Currently, when you try to edit the description of a project, if that description is too long, it will open like this. The `textarea` does not account for length of words. 

We need to open the description box to match the amount of words in there.

Maybe switch in favor of a `Material-UI` textarea instead and see if that does anything. 

<img width="536" alt="Screen Shot 2020-06-22 at 11 58 37 PM" src="https://user-images.githubusercontent.com/32604574/85359520-76638c00-b4e4-11ea-9e3a-14220f3b6b40.png">

**Comment by lenghuang** [comment]
[Material UI Docs](https://material-ui.com/components/textarea-autosize/) that could be useful for this. Something @Rongfengye can look into.

**Comment by Rongfengye** [comment]
ill take this
